[package]
name = "cddl-codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
cbor_event = "2.1.3"
cddl = "0.8.7"
clap = { version = "~3.1.5", features = ["derive"] }
codegen = "0.1.3"
either = "1.7.0"
once_cell = "1.10.0"
